name: tvm-upgrade
version: 2.2.4
usage: Please see https://github.com/trilioData/tvm-helm-plugins for usage
description: Push chart package to ChartMuseum
ignoreFlags: false
platformCommand:
  - os: linux
    arch: i386
    command: $HELM_PLUGIN_DIR/dist/tvm-upgrade_linux_386/tvm-upgrade
  - os: linux
    arch: amd64
    command: $HELM_PLUGIN_DIR/dist/tvm-upgrade_linux_amd64/tvm-upgrade
  - os: windows
    arch: amd64
    command: $HELM_PLUGIN_DIR/dist/tvm-upgrade_windows_amd64/tvm-upgrade.exe
  - os: windows
    arch: i386
    command: $HELM_PLUGIN_DIR/dist/tvm-upgrade_windows_386/tvm-upgrade.exe
  - os: darwin
    arch: amd64
    command: $HELM_PLUGIN_DIR/dist/tvm-upgrade_darwin_amd64/tvm-upgrade
