on:
  push:
    tags:
      - 'v*.*.*'
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Release with GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} 
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - uses: pocket-apps/action-update-version@v1
        with:
          files: 'plugin.yaml'
          version-regexp: '\d+.\d+.\d+'
          repo-token: ${{ secrets.TOKEN }}
